Added target sync, minor code cleanup.
kdreese/godot-3D-shooter-project pull request #27
Opened 2022-12-04 01:48 UTC by admoore0

2022-12-06 23:03 UTC, thearst3rd requested changes
Awesome work dude! I tested it and didn't encounter any issues between two players. There is one bug I noticed in the code and like some other tiny things

2022-12-06 23:03 UTC, thearst3rd commented on src/states/Game.gd
> +		sync_targets()
I don't think we need a variable `targets`, the only time it's set is on line 89 where it calls `select_targets()` but then it calls it again on the next line so it's going entirely unused

2022-12-06 23:03 UTC, thearst3rd commented on src/states/Game.gd
> +		sync_targets()
`sync_targets(player_id)` to prevent connected clients getting their targets duplicated when a new client joins

2022-12-06 23:03 UTC, thearst3rd commented on src/states/Scoreboard.gd
> +	var id = MultiplayerInfo.get_player_id()
pedantic - `:=`

2022-12-06 23:05 UTC, admoore0 commented on src/states/Game.gd
> +		sync_targets()
Agree

2022-12-06 23:05 UTC, admoore0 commented on src/states/Game.gd
> +		sync_targets()
Yup, i meant to do that here.

2022-12-06 23:06 UTC, admoore0 commented on src/states/Scoreboard.gd
> +	var id = MultiplayerInfo.get_player_id()
For some reason the editor complained when I tried it last time. Not sure why

2022-12-06 23:10 UTC, thearst3rd commented on src/states/Scoreboard.gd
> +	var id = MultiplayerInfo.get_player_id()
Huh you're right... I think it needs to have a `class_name` so it can "register" the `get_player_id() -> int` function and its return type

2022-12-06 23:11 UTC, admoore0 commented on src/states/Scoreboard.gd
> +	var id = MultiplayerInfo.get_player_id()
I'll try that

2022-12-06 23:23 UTC, admoore0 commented on src/states/Scoreboard.gd
> +	var id = MultiplayerInfo.get_player_id()
The class name had to have a different name from the singleton, but that was fine. Is there a reason to not just always add a class name to our scripts?

2022-12-09 02:22 UTC, kdreese approved these changes

2022-12-09 02:47 UTC, thearst3rd approved these changes

2022-12-09 02:47 UTC, merged