Refactor the color button circles to be more consistent
kdreese/godot-3D-shooter-project pull request #50
Opened 2023-02-10 03:24 UTC by thearst3rd

2023-02-10 03:25 UTC, admoore0 approved these changes, later dismissed

2023-02-10 16:04 UTC, kdreese requested changes

2023-02-10 16:04 UTC, kdreese commented on src/objects/ColorButton.gd
> +	print("Setting button size: %.2f" % scale)
Remove print statement

2023-02-17 00:29 UTC, kdreese approved these changes

2023-02-17 00:39 UTC, admoore0 approved these changes

2023-02-17 00:42 UTC, merged